services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - warehouse_app_network

  db:
    image: postgres:14
    container_name: warehouse_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - warehouse_app_network

volumes:
  postgres_data:

networks:
  warehouse_app_network:
    driver: bridge
